//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserADInfo", Namespace="http://schemas.datacontract.org/2004/07/IntegrationTire.Contracts")]
    public partial class UserADInfo : object
    {
        
        private string ColleageIdField;
        
        private string ColleageNameField;
        
        private string DepartmentIdField;
        
        private string DepartmentNameField;
        
        private string EmailField;
        
        private string EmpClassField;
        
        private string EmpTypeField;
        
        private string EmployeeIDField;
        
        private string FullNameArField;
        
        private string FullNameEnField;
        
        private System.Nullable<decimal> GPAField;
        
        private System.Nullable<bool> GenderField;
        
        private string JobTitleField;
        
        private string MobileField;
        
        private string NationalityField;
        
        private string PhoneField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColleageId
        {
            get
            {
                return this.ColleageIdField;
            }
            set
            {
                this.ColleageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColleageName
        {
            get
            {
                return this.ColleageNameField;
            }
            set
            {
                this.ColleageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpClass
        {
            get
            {
                return this.EmpClassField;
            }
            set
            {
                this.EmpClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpType
        {
            get
            {
                return this.EmpTypeField;
            }
            set
            {
                this.EmpTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                this.EmployeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameAr
        {
            get
            {
                return this.FullNameArField;
            }
            set
            {
                this.FullNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameEn
        {
            get
            {
                return this.FullNameEnField;
            }
            set
            {
                this.FullNameEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GPA
        {
            get
            {
                return this.GPAField;
            }
            set
            {
                this.GPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle
        {
            get
            {
                return this.JobTitleField;
            }
            set
            {
                this.JobTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentMainInfo", Namespace="http://schemas.datacontract.org/2004/07/IntegrationTire.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.StudentInfo))]
    public partial class StudentMainInfo : object
    {
        
        private string CollegeCodeField;
        
        private string CollegeNameField;
        
        private string DeptCodeField;
        
        private string DeptNameField;
        
        private string EmailField;
        
        private string FullNameArField;
        
        private System.Nullable<decimal> GPAField;
        
        private string LevelField;
        
        private string NationalityField;
        
        private string SSNField;
        
        private string StudentTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollegeCode
        {
            get
            {
                return this.CollegeCodeField;
            }
            set
            {
                this.CollegeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollegeName
        {
            get
            {
                return this.CollegeNameField;
            }
            set
            {
                this.CollegeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode
        {
            get
            {
                return this.DeptCodeField;
            }
            set
            {
                this.DeptCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName
        {
            get
            {
                return this.DeptNameField;
            }
            set
            {
                this.DeptNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameAr
        {
            get
            {
                return this.FullNameArField;
            }
            set
            {
                this.FullNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GPA
        {
            get
            {
                return this.GPAField;
            }
            set
            {
                this.GPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN
        {
            get
            {
                return this.SSNField;
            }
            set
            {
                this.SSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentType
        {
            get
            {
                return this.StudentTypeField;
            }
            set
            {
                this.StudentTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentInfo", Namespace="http://schemas.datacontract.org/2004/07/IntegrationTire.Contracts")]
    public partial class StudentInfo : ServiceReference1.StudentMainInfo
    {
        
        private int EarnedHoursField;
        
        private bool IsMaleField;
        
        private string SpecializationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EarnedHours
        {
            get
            {
                return this.EarnedHoursField;
            }
            set
            {
                this.EarnedHoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMale
        {
            get
            {
                return this.IsMaleField;
            }
            set
            {
                this.IsMaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialization
        {
            get
            {
                return this.SpecializationField;
            }
            set
            {
                this.SpecializationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUsersManager")]
    public interface IUsersManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/FindUserInActiveDirectory", ReplyAction="http://tempuri.org/IUsersManager/FindUserInActiveDirectoryResponse")]
        System.Threading.Tasks.Task<ServiceReference1.UserADInfo> FindUserInActiveDirectoryAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/FindUserInRepository", ReplyAction="http://tempuri.org/IUsersManager/FindUserInRepositoryResponse")]
        System.Threading.Tasks.Task<ServiceReference1.UserADInfo> FindUserInRepositoryAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/FindExUserPhone", ReplyAction="http://tempuri.org/IUsersManager/FindExUserPhoneResponse")]
        System.Threading.Tasks.Task<string> FindExUserPhoneAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetStdData", ReplyAction="http://tempuri.org/IUsersManager/GetStdDataResponse")]
        System.Threading.Tasks.Task<ServiceReference1.StudentInfo> GetStdDataAsync(string AcademicNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IUsersManagerChannel : ServiceReference1.IUsersManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class UsersManagerClient : System.ServiceModel.ClientBase<ServiceReference1.IUsersManager>, ServiceReference1.IUsersManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsersManagerClient() : 
                base(UsersManagerClient.GetDefaultBinding(), UsersManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IUsersManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(UsersManagerClient.GetBindingForEndpoint(endpointConfiguration), UsersManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsersManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsersManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UserADInfo> FindUserInActiveDirectoryAsync(string userName)
        {
            return base.Channel.FindUserInActiveDirectoryAsync(userName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UserADInfo> FindUserInRepositoryAsync(string userName)
        {
            return base.Channel.FindUserInRepositoryAsync(userName);
        }
        
        public System.Threading.Tasks.Task<string> FindExUserPhoneAsync(string userName)
        {
            return base.Channel.FindExUserPhoneAsync(userName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StudentInfo> GetStdDataAsync(string AcademicNumber)
        {
            return base.Channel.GetStdDataAsync(AcademicNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IUsersManager))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IUsersManager))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://bld01.ekfu.local/UsersManager.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UsersManagerClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IUsersManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UsersManagerClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IUsersManager);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IUsersManager,
        }
    }
}
